# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fdd5ee03bc646f0ffed7b2ba6c14b33d352dab4227096cdbc379155b47b75b5ad0ff8ab88d9dadb67e7dde7a60add3b35e77525b6fedebbb03d4377332e98c9

test:
  secret_key_base: 8258112e83f3300d7ce8fecdade67505d72b78a40f110393e6ca0edfe0d2997082cf9aaa046215efe25bae6e9ae99b69bf335414f5ee1bcd561118c6f92a3547

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
